theme: jekyll-theme-slate

# Site settings
title: Society of Gaming culture
email: info@sogc.nu
description: Din lokala spelförening i Osby. # this means to ignore newlines until "baseurl:"
url: "" # the base hostname & protocol for your site
