theme: jekyll-theme-dinky

# Site settings
title: Society of Gaming culture
email: info@sogc.nu
description: > # this means to ignore newlines until "baseurl:"
url: "" # the base hostname & protocol for your site
